name: "Plugin release"

on:
  push:
    tags:
       - '*'

jobs:
  continuous-integration:
    name: "GLPI ${{ matrix.glpi-version }} - php:${{ matrix.php-version }} - ${{ matrix.db-image }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - {glpi-version: "10.0.x", php-version: "7.4", db-image: "mysql:5.7"}
          - {glpi-version: "10.0.x", php-version: "8.0", db-image: "mysql:8.0"}
          - {glpi-version: "10.0.x", php-version: "8.1", db-image: "mariadb:10.2"}
          - {glpi-version: "10.0.x", php-version: "8.2", db-image: "mariadb:11.0"}
          - {glpi-version: "10.0.x", php-version: "8.3-rc", db-image: "mysql:8.0"}
    uses: "glpi-project/plugin-ci-workflows/.github/workflows/continuous-integration.yml@v1"
    with:
      plugin-key: ${{ github.event.repository.name }}
      glpi-version: "${{ matrix.glpi-version }}"
      php-version: "${{ matrix.php-version }}"
      db-image: "${{ matrix.db-image }}"

  bump-version:
    name: "Bump version"
    runs-on: "ubuntu-latest"
    needs: continuous-integration
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0 #To Fetch All Tags and Branches

      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          dev: no

      #####################################################################################
      ## Extract some variables                                                          ##
      ## repo_name          -> plugin repo name (to UPPER CASE)             ex : TAG     ##
      ## tag_name           -> tag name                                     ex : 2.1.2   ##
      ## plugin_version     -> current plugin version define in 'setup.php' ex : 2.1.0   ##
      ## min_glpi_version   -> min glpi version define in 'setup.php'       ex : 10.0.0  ##
      ## max_glpi_version   -> max glpi version define in 'setup.php'       ex : 10.0.99 ##
      #####################################################################################
      - name: Extract needed env variables
        run: |
             echo "repo_name=${{ github.event.repository.name }}" | tr '[:lower:]' '[:upper:]' >> $GITHUB_ENV
             echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
             echo "plugin_version=$(grep -oP 'define\("PLUGIN_${{ env.repo_name }}_VERSION", "\K[^"]+' setup.php)" >> $GITHUB_ENV
             echo "min_glpi_version=$(grep -oP 'define\("PLUGIN_${{ env.repo_name }}_MIN_GLPI", "\K[^"]+' setup.php)" >> $GITHUB_ENV
             echo "max_glpi_version=$(grep -oP 'define\("PLUGIN_${{ env.repo_name }}_MAX_GLPI", "\K[^"]+' setup.php)" >> $GITHUB_ENV

      - name: Show env variables
        run: echo ${{ env }}

      #####################################################################################
      ## Replaces the plugin constant that defines this version                          ##
      ## define('PLUGIN_${{ env.repo_name }}_VERSION', '${{ env.tag_name }}');           ##
      #####################################################################################
      - name: Update setup.php
        run: sed -i "s/define('PLUGIN_${{ env.repo_name }}_VERSION', ''${{ env.plugin_version }}'');/define('PLUGIN_${{ env.repo_name }}_VERSION', '${{ env.tag_name }}');/g" setup.php

      ###################################################################################################################################################################################################################
      ## Update the plugin.xml file to add new version                                                                                                                                                                 ##
      ## <version>                                                                                                                                                                                                     ##
      ##    <num>${{ env.tag_name }}</num>                                                                                                                                                                             ##
      ##    <compatibility>>=${{ env.min_glpi_version }} <=${{ env.max_glpi_version }}</compatibility>                                                                                                                 ##
      ##    <download_url>https://github.com/pluginsGLPI/${{ github.event.repository.name }}/releases/download/${{ env.tag_name }}/glpi-${{ github.event.repository.name }}-${{ env.tag_name }}.tar.bz2</download_url> ##
      ## </version>                                                                                                                                                                                                    ##
      ###################################################################################################################################################################################################################
      - name: Update plugin.xml
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: >
                ed --omit-decl -P -L -i '//versions//version[1]' -t elem -n "version"
                -s '//versions/version[1]' -t elem -n "num" -v "${{ env.tag_name }}"
                -s '//versions/v-ersion[1]' -t elem -n "compatibility" -v ">=${{ env.min_glpi_version }} <=${{ env.max_glpi_version }}"
                -s '//versions/version[1]' -t elem -n "download_url" -v "https://github.com/pluginsGLPI/${{ github.event.repository.name }}/releases/download/${{ env.tag_name }}/glpi-${{ github.event.repository.name }}-${{ env.tag_name }}.tar.bz2" plugin.xml

      #####################################################################################
      ## Format 'plugin.xml'                                                             ##
      ## -o                -> omit xml declaration <?xml version="1.0"?>                 ##
      ## --indent-spaces 3 -> indent with 3 spaces                                       ##
      ## -e utf-8          -> encode with utf-8                                          ##
      #####################################################################################
      - name: Format and clean up
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: |
                fo -o --indent-spaces 3 -e utf-8 plugin.xml > format.xml
                unesc format.xml > plugin.xml

      - name: Clean up
        run: |
             rm -fr format.xml

      - name: cat plugin.xml
        run: cat plugin.xml

      - name: cat setup.php
        run: cat setup.php


  create-release:
    name: "Create release"
    runs-on: "ubuntu-latest"
    needs: bump-version
    steps:
      - name: "Extract Current Tag Name"
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Build package"
        id: "build-package"
        uses: "glpi-project/tools/github-actions/build-package@0.7.1"
        with:
          plugin-version: ${{ env.tag_name }}

      - name: "Create release"
        id: "create-release"
        uses: "actions/create-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: ${{ env.tag_name }}
          draft: true

      - name: "Attach package to release"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ steps.build-package.outputs.package-path }}
          asset_name: ${{ steps.build-package.outputs.package-basename }}
          asset_content_type: " application/x-bzip2"
